// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBltTd5sAdR2C-5upuQi_7wM-401XAX_pY',
    appId: '1:419141610642:web:ed45b19a779202e7ad0a4b',
    messagingSenderId: '419141610642',
    projectId: 'flutter-4ce58',
    authDomain: 'flutter-4ce58.firebaseapp.com',
    databaseURL: 'https://flutter-4ce58-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-4ce58.appspot.com',
    measurementId: 'G-E4L62MQBBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5NsuwT8IZ6y0tnyeSj4eroANqTUqhzUA',
    appId: '1:170773391331:android:a08fdf732273c668b1a2d6',
    messagingSenderId: '170773391331',
    projectId: 'tiktok-clone-6fda2',
    databaseURL: '', 
    storageBucket: 'tiktok-clone-6fda2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFf4QDMFeqN9ukMyH7vYJCBDM8AMtOS84',
    appId: '1:419141610642:ios:ac6e742b479863e6ad0a4b',
    messagingSenderId: '419141610642',
    projectId: 'flutter-4ce58',
    databaseURL: 'https://flutter-4ce58-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-4ce58.appspot.com',
    iosClientId:
        '419141610642-qu561eq5r5bk5sv676t0cn105jhhf9e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFf4QDMFeqN9ukMyH7vYJCBDM8AMtOS84',
    appId: '1:419141610642:ios:ac6e742b479863e6ad0a4b',
    messagingSenderId: '419141610642',
    projectId: 'flutter-4ce58',
    databaseURL: 'https://flutter-4ce58-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-4ce58.appspot.com',
    iosClientId:
        '419141610642-qu561eq5r5bk5sv676t0cn105jhhf9e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
